### ISSUE TITLE
Contribution Month Select Dropdown changed month order

### ISSUE THREAD

**Issue by Sinjhin** [donejs/bitcentive#81] opened 2016-09-20 23:17 UTC
It went from Sept, Oct to:
![screen shot 2016-09-20 at 6 15 45 pm](https://cloud.githubusercontent.com/assets/1085104/18692236/6fd4fa32-7f5e-11e6-8286-6c5bdfa2220d.png)

**Comment by DesignByOnyx** [comment] 2016-11-29 19:23
We should figure out the client-side sorting to make sure data is always displayed in the correct order, but this can also be fixed if the server returns sorted data.

**Comment by obaidott** [comment] 2016-11-29 21:19
@DesignByOnyx we do have a set of algebra on the client side to take care of this (https://github.com/donejs/bitcentive/blob/staging/public/models/algebras.js#L4). 

I am not able to reproduce this on the latest staging branch. Are you able to re-create this issue on your end?

**Comment by DesignByOnyx** [comment] 2016-11-29 23:00
Right now, it displays things in database order. In a perfect world, the months will get created in chronological order. However, if the items in the DB are created in a non-linear order, the UI shows the items in that order. This tells me the algebra is not working the way it should.

For example, I had December 2016 through March 2017 in my database. I updated the database directly, changing February to October (`02` -> `10`). And October appears in February's position:

![image](https://cloud.githubusercontent.com/assets/514040/20732645/f669b31a-b64c-11e6-9291-9b7ca9b63f43.png)

**Comment by DesignByOnyx** [comment] 2016-11-30 18:38
The work I am doing for #71 should fix this issue.

**Comment by DesignByOnyx** [comment] 2016-11-30 23:06
#155 makes sure that data is sorted by date on the server side (if no $sort parameter is specified).

**Comment by DesignByOnyx** [comment] 2016-12-01 16:11
@marshallswq - OK, so sorting is no longer done server side. The problem seems to be that feathers client is stripping any parameters from GET requests. I tried `{$sort: {date: 1}}` to no avail, alos tried `{foo: "bar"} - the params are being stripped before the socket request is sent to the server.

**Comment by marshallswain** [comment] 2016-12-01 21:02
This should be fixed with this PR: https://github.com/canjs/can-connect-feathers/pull/35

**Closed** 2016-12-01 21:16 UTC
Labels: bug, in progress, P1
