### ISSUE TITLE
Dashboard does not work correctly (bit-contribution-month component)

### ISSUE THREAD

**Issue by ilyavf** [donejs/bitcentive#98] opened 2016-11-11 15:30 UTC
Bugs:
 - [x] Name field of OSProjects is displayed as empty after page refreshing.
 - [x] Name field of  CProjects is not shown at all.
 - [x] When adding a CProject the whole component can dissapear.
 - [x] When added a client in CProject and removed it, it does not appear in the dropdown list.

**Comment by DesignByOnyx** [comment] 2016-11-29 19:21
Most of this should have been fixed by #119 and/or other updates as I am not seeing these issues any more.

**Comment by obaidott** [comment] 2016-11-29 21:16
I can't reproduced these issues either after updated to latest staging with can-connect-feathers. I am going to close this ticket.

**Closed by obaidott** 2016-11-29 21:16 UTC
Labels: bug, P1
