### ISSUE TITLE
Open Source Projects not displaying

### ISSUE THREAD

**Issue by Sinjhin** [donejs/bitcentive#70] opened 2016-09-19 16:28 UTC
![bitcentive](https://cloud.githubusercontent.com/assets/1085104/18640089/39b91be8-7e5c-11e6-87b4-199068dc1b6a.png)

**Comment by obaidott** [comment] 2016-11-28 20:04
I am not able to reproduce this issue. Not sure if it is being caused by invalid local cache? 

cc: @BigAB

**Comment by BigAB** [comment] 2016-11-28 21:47
This probably was caused by a model issue that is now fixed.

Closing

**Closed by BigAB** 2016-11-28 21:47 UTC
Labels: bug, P1
