### ISSUE TITLE
make session automatically call createInstance

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#148] opened 2016-11-29 22:05 UTC
window.authAgent.on('login', function (token) {

});

**Comment by BigAB** [comment] 2016-11-30 17:41
Related or duplicate of #87 ?

**Comment by marshallswain** [comment] 2016-12-01 22:44
This is done in the can-connect-feathers@2.0.0-beta.8 release.

**Closed by marshallswain** 2016-12-01 22:44 UTC
Labels: enhancement
