### ISSUE TITLE
Implement Contribution Point decay

### ISSUE THREAD

**Issue by BigAB** [donejs/bitcentive#161] opened 2016-12-02 22:14 UTC
Yearly, the value of a contribution decays to half it's value, until it is below **1**, then it has no more value.

This could be done in the calculation of $ share, halving contribution values year after year going backwards.

Perhaps this needs ore thought, but should be implemented before 1 year of contributions is added.

**Comment by imaustink** [comment] 2017-09-14 15:30
@justinbmeyer a few questions on this:

1) I am assuming the value to be decayed is the number of story points. Am I correct? Or should the math be done downstream on the calculated dollar value itself?

2) The more I dig into the code and understand things, the less confident I feel about how and where to implement, for lack of a better term, the "previous months" cache. Perhaps you could help me visualize it with a little bit of pseudo code, or maybe it would be better to get on Screen Hero when you have a few free moments to discuss it.

3) I think I found what most of the performance issues are caused by. It seems we're calling the [`OSProjectContributionsMap`](https://github.com/donejs/bitcentive/blob/staging/public/models/contribution-month/contribution-month.js#L288) method hundreds of times with the same values, and this grows with the dataset. I think implementing a cache is the way to fix this. I have a good idea of how this should work but I don't have an idea on a clean way to know when the cache should be cleared. Especially if we implement decay in that method.

4) I don't believe this is related to decay but I would still like to know. Since the training, I have forgotten how hourly tax works. If it's not too complex, could you explain that again, please?

**Comment by justinbmeyer** [comment] 2017-09-14 15:43
1 - points

**Comment by justinbmeyer** [comment] 2017-09-14 15:43
2- on the ContributionMonth.List

**Comment by justinbmeyer** [comment] 2017-09-14 15:44
3- use a computed (getter) property and the cache should update itself

**Comment by justinbmeyer** [comment] 2017-09-14 15:45
4 - read the program charter. It's in Bitovi/Bitovi repo

**Comment by imaustink** [comment] 2017-09-26 18:04
Closed by #333

**Closed by imaustink** 2017-09-26 18:04 UTC
Labels: enhancement
